version: '2.2'
services:
  redis-server:
    image: healthcheck/redis:alpine
    networks:
      private:
        aliases:
        - redis-server
  application:
    restart: on-failure
#    depends_on:
#      redis-server:
#        condition: service_healthy
    build: .
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      HTTP_PORT: 3000
    networks:
      private:
        aliases:
        - application
  proxy:
    restart: on-failure
#    depends_on:
#      application:
#        condition: service_healthy
    image: nginx:1.15.5-alpine
    volumes: ['./nginx/default.conf:/etc/nginx/conf.d/default.conf']
    ports: ['80:80']
    networks:
      private:
        aliases: []
      public:
        aliases: []
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:80/api/health || exit 1
      timeout: 1s
      retries: 99
networks:
  private:
    driver: bridge
  public:
    driver: bridge
