version: '2.2'
services:
  redis:
    image: healthcheck/redis:alpine
    ports: ['6379:6379']
  app:
    depends_on:
      redis:
        condition: service_healthy
    build: .
    ports: ['3000:3000']
    environment:
      PORT: 3000
      REDIS_HOST: redis
